/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppTodoListIdRouteImport } from './routes/_app/$todoListId'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodoListIdRoute = AppTodoListIdRouteImport.update({
  id: '/_app/$todoListId',
  path: '/$todoListId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$todoListId': typeof AppTodoListIdRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/$todoListId': typeof AppTodoListIdRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/$todoListId': typeof AppTodoListIdRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$todoListId' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$todoListId' | '/'
  id: '__root__' | '/_app/$todoListId' | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppTodoListIdRoute: typeof AppTodoListIdRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$todoListId': {
      id: '/_app/$todoListId'
      path: '/$todoListId'
      fullPath: '/$todoListId'
      preLoaderRoute: typeof AppTodoListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppTodoListIdRoute: AppTodoListIdRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
